install.packages("tm")
require("tm")
install.packages("corpus")
install.packages("ggplot2")
install.packages("textreuse")
install.packages("devtools")

my.corpus<-Corpus(DirSource("Text Files"))
my.corpus<-tm_map(my.corpus,removeWords,stopwords("english"))
my.tdm<-TermDocumentMatrix(my.corpus)
#inspect(my.tdm)
my.dtm<-DocumentTermMatrix(my.corpus,control=list(weighting=weightTfldf,stopwords=TRUE))
#inspect(my.dtm)
my.df<-as.data.frame(inspect(my.tdm))
my.df.scale<-scale(my.df)
d<-dist(my.df.scale,method = "euclidean")
fit<-hclust(d,method = "ward.D")
plot(fit) 