library(igraph)
getwd()
nodes <- read.csv("C:/Users/Merin/OneDrive/Documents/MSC I/nodes.csv")
head(nodes)
links <- read.csv("C:/Users/Merin/OneDrive/Documents/MSC I/edges.csv")
head(links)
net <- graph.data.frame(d=links, vertices=nodes, directed=T)
m=as.matrix(net)
get.adjacency(m)
plot(net)
